// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8mYyPrl_qhPbYUN-2FCunTFm1DE0elY',
    appId: '1:139010987790:web:34c5a12b2a96160adfa95f',
    messagingSenderId: '139010987790',
    projectId: 'directionproject-1e798',
    authDomain: 'directionproject-1e798.firebaseapp.com',
    databaseURL: 'https://directionproject-1e798-default-rtdb.firebaseio.com',
    storageBucket: 'directionproject-1e798.appspot.com',
    measurementId: 'G-R5HN8528KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJrocqX3N4DY5C32Ry-qqCSJMPn8IKFA',
    appId: '1:139010987790:android:fa100f55a1c4b4b2dfa95f',
    messagingSenderId: '139010987790',
    projectId: 'directionproject-1e798',
    databaseURL: 'https://directionproject-1e798-default-rtdb.firebaseio.com',
    storageBucket: 'directionproject-1e798.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZXGlEdhXMIozsg0lcNX0XDEIkX5URZ20',
    appId: '1:139010987790:ios:71902291beb35ee7dfa95f',
    messagingSenderId: '139010987790',
    projectId: 'directionproject-1e798',
    databaseURL: 'https://directionproject-1e798-default-rtdb.firebaseio.com',
    storageBucket: 'directionproject-1e798.appspot.com',
    iosBundleId: 'com.example.direction',
  );
}
